// Template from setup-effect-toolchain. Keep these ignores in step with oxlint.config.ts.
import { defineConfig } from "oxfmt";
import ultracite from "ultracite/oxfmt";

export default defineConfig({
  ...ultracite,
  ignorePatterns: [
    ...(ultracite.ignorePatterns ?? []),
    "**/dist/**",
    // Fetched upstream repos, and skills sync writes byte for byte from them.
    ".upstream/**",
    // Its skill list is generated by `bun run skills readme` and compared by check.
    "README.md",
    "skills/**",
    // Installed agent skills and agent config are not project source.
    ".agent/**",
    ".agents/**",
    ".claude/**",
    ".codex/**",
    ".continue/**",
    ".cursor/**",
    ".gemini/**",
    ".opencode/**",
    ".pi/**",
    ".roo/**",
    ".windsurf/**",
    "tools/oxlint/anti-slop/**",
  ],
});
