// Template from setup-effect-toolchain. Delete the REACT blocks in repos without React.
import { defineConfig } from "oxlint";
import { recommended as effectRecommended } from "oxlint-plugin-effect/presets/recommended";

const effectStyleRules = {
  "effect-shape/no-arrow-ladder": "error",
  "effect-shape/no-atom-registry-effect-sync": "error",
  "effect-shape/no-branch-in-object": "error",
  "effect-shape/no-call-tower": "error",
  "effect-shape/no-effect-all-step-sequencing": "error",
  "effect-shape/no-effect-as": "error",
  "effect-shape/no-effect-bind": "error",
  "effect-shape/no-effect-callback": "error",
  "effect-shape/no-effect-catch-ladder": "error",
  "effect-shape/no-effect-do": "error",
  "effect-shape/no-effect-fn-callback-alias": "error",
  "effect-shape/no-effect-fn-untraced": "error",
  "effect-shape/no-effect-gen-callback-alias": "error",
  "effect-shape/no-effect-ladder": "error",
  "effect-shape/no-effect-never": "error",
  "effect-shape/no-effect-run-in-test": "error",
  "effect-shape/no-effect-runfork": "error",
  "effect-shape/no-effect-side-effect-wrapper": "error",
  "effect-shape/no-effect-sleep-in-test": "error",
  "effect-shape/no-effect-succeed-variable": "warn",
  // Duplicated by effect/noGlobals.
  "effect-shape/no-effect-sync-console": "off",
  "effect-shape/no-effect-type-alias": "error",
  "effect-shape/no-family-collection-read": "error",
  "effect-shape/no-flatmap-ladder": "warn",
  "effect-shape/no-fragmented-const-assembly": "error",
  "effect-shape/no-iife-wrapper": "error",
  "effect-shape/no-inline-runtime-provide": "error",
  "effect-shape/no-manual-data-guard": "error",
  "effect-shape/no-match-effect-branch": "error",
  "effect-shape/no-match-tag-neutral-fallback": "warn",
  "effect-shape/no-match-void-branch": "error",
  "effect-shape/no-naked-object-state-update": "error",
  "effect-shape/no-native-current-time": "off",
  "effect-shape/no-nested-effect-call": "error",
  "effect-shape/no-option-as": "error",
  "effect-shape/no-option-boolean-normalization": "error",
  "effect-shape/no-option-effect-branch": "warn",
  "effect-shape/no-option-nullish-rewrap": "error",
  "effect-shape/no-pipe-ladder": "error",
  "effect-shape/no-pipeline-fragment-staging": "error",
  "effect-shape/no-react-state": "error",
  "effect-shape/no-render-side-effects": "error",
  "effect-shape/no-return-in-arrow": "warn",
  "effect-shape/no-return-in-callback": "warn",
  "effect-shape/no-schema-sync-in-effect-generator": "error",
  "effect-shape/no-switch-statement": "error",
  // Duplicated by effect/noThrowStatement.
  "effect-shape/no-throw-in-effect-generator": "off",
  "effect-shape/no-try-catch": "error",
  "effect-shape/no-unknown-boolean-coercion-helper": "error",
  "effect-shape/no-wrapgraphql-catch": "error",
  "effect-shape/prefer-assert-in-effect-test": "warn",
  "effect-shape/prefer-effect-async": "warn",
  "effect-shape/prefer-effect-cache": "warn",
  // Duplicated by effect/noGlobals or effect/noNodeBuiltinImport.
  "effect-shape/prefer-effect-child-process": "off",
  "effect-shape/prefer-effect-config": "off",
  "effect-shape/prefer-effect-date-time": "off",
  "effect-shape/prefer-effect-file-system": "off",
  "effect-shape/prefer-effect-fn": "error",
  "effect-shape/prefer-effect-http-client": "off",
  "effect-shape/prefer-effect-logging": "off",
  "effect-shape/prefer-effect-random": "off",
  "effect-shape/prefer-effect-scheduling": "off",
  "effect-shape/prefer-effect-test-layer": "warn",
  "effect-shape/prefer-effect-vitest": "error",
  "effect-shape/prefer-match-tags": "error",
  "effect-shape/prefer-match-value-tags": "warn",
  "effect-shape/prefer-schema-json": "off",
  "effect-shape/prevent-dynamic-imports": "error",
  "effect-shape/require-return-yield-effect-terminal": "error",
  "effect-shape/warn-effect-sync-wrapper": "warn",
} satisfies Record<string, "error" | "off" | "warn">;

const ignorePatterns = [
  "**/dist",
  "**/node_modules",
  "**/build",
  "**/.output",
  "**/.turbo",
  "**/.vite",
  "**/coverage",
  "**/*.gen.*",
  "**/*.generated.*",
  "**/generated",
  "**/__generated__",
  "**/*.d.ts.map",
  "**/bun.lock",
  // Fetched upstream repos, and skills sync writes byte for byte from them.
  ".upstream/**",
  "skills/**",
  ".agent/**",
  ".agents/**",
  ".claude/**",
  ".codex/**",
  ".continue/**",
  ".cursor/**",
  ".gemini/**",
  ".opencode/**",
  ".pi/**",
  ".roo/**",
  ".windsurf/**",
  "tools/oxlint/anti-slop/**",
];

export default defineConfig({
  env: {
    browser: true,
    es2022: true,
    node: true,
  },
  ignorePatterns,
  jsPlugins: [
    { name: "effect", specifier: "oxlint-plugin-effect/plugin" },
    { name: "effect-shape", specifier: "@shekohex/oxc-effect" },
    {
      name: "anti-slop",
      specifier: "./tools/oxlint/anti-slop/index.ts",
    },
    {
      name: "anti-slop-effect",
      specifier: "./tools/oxlint/anti-slop/effect/index.ts",
    },
  ],
  overrides: [
    {
      files: ["**/*.{test,spec}.{ts,tsx,js,jsx}"],
      rules: {
        "promise/prefer-await-to-then": "off",
      },
    },
  ],
  plugins: ["typescript", "unicorn", "oxc", "import", "promise"],
  rules: {
    ...effectRecommended,
    ...effectStyleRules,
    // anti-slop: only the rules no other plugin owns (see rule-ownership.md).
    "anti-slop-effect/no-service-constructor-imports": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-unknown-returns": "error",
    // The code-shape plugin owns these duplicated policies.
    "effect/noDynamicImports": "off",
    "effect/noEffectBind": "off",
    "effect/noEffectDo": "off",
    "effect/noSequentialEffectAll": "off",
    "effect/noTryCatch": "off",
    "effect/preferEffectFn": "off",
    "effect/preferMatchTagsExhaustive": "error",
    "func-style": "off",
    "import/no-cycle": "warn",
    "import/no-duplicates": "error",
    "import/no-self-import": "error",
    "no-use-before-define": "off",
    "promise/no-multiple-resolved": "error",
    "promise/no-return-wrap": "error",
    "promise/param-names": "error",
    "promise/prefer-await-to-then": "error",
    "promise/valid-params": "error",
    "typescript/consistent-type-imports": "error",
    // Type-aware, run only with oxlint-tsgolint installed and `--type-aware`: no-floating-promises,
    // no-misused-promises, no-unnecessary-type-assertion, switch-exhaustiveness-check.
    "typescript/no-floating-promises": "error",
    "typescript/no-import-type-side-effects": "error",
    "typescript/no-misused-promises": "error",
    "typescript/no-unnecessary-type-assertion": "warn",
    "typescript/switch-exhaustiveness-check": "error",
    "unicorn/no-abusive-eslint-disable": "error",
    "unicorn/no-document-cookie": "error",
    "unicorn/no-invalid-fetch-options": "error",
    "unicorn/no-useless-undefined": "error",
  },
});
